# Generated by Django 5.1.1 on 2024-10-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='foodName',
        ),
    ]
