# Generated by Django 5.1.1 on 2024-10-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_rename_name_menu_foodname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='foodName',
            new_name='name',
        ),
    ]
