# Generated by Django 5.1.1 on 2024-10-08 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_rename_foodname_menu_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='menu',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='testApp.menucategory'),
        ),
    ]
